'use client';

import { useState } from 'react';
import type { RowVerdict } from '@core/data/store/supplyCsv';
import { previewSupplyCsv, applySupplyCsv } from '@/app/admin/store/import/actions';

/**
 * Filling in fifty products' costs without opening fifty pages.
 *
 * PREVIEW THEN APPLY, ALWAYS
 * --------------------------
 * Nothing is written until the operator has seen, row by row, what would
 * happen. Both steps run the same validation on the server, so the list they
 * approved and the writes that follow cannot differ — a preview generated by
 * different code from the write manufactures confidence rather than earning it.
 *
 * WHY REJECTED ROWS DO NOT STOP THE IMPORT
 * ----------------------------------------
 * A spreadsheet with forty-eight good rows and two typos should import
 * forty-eight and name the two. Refusing the file means finding the typos by
 * bisection, and people who have to do that go back to editing one product at a
 * time — which is the thing this screen exists to end.
 */
export const SupplyImport: React.FC = () => {
  const [csv, setCsv] = useState('');
  const [fileName, setFileName] = useState('');
  const [verdicts, setVerdicts] = useState<RowVerdict[] | null>(null);
  const [counts, setCounts] = useState({ apply: 0, skip: 0, reject: 0 });
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [done, setDone] = useState<string | null>(null);

  return (
    <section className="admin-section" aria-labelledby="import-h" data-testid="supply-import">
      <h2 id="import-h">استيراد التكاليف من ملف</h2>
      <p style={{ margin: '0 0 14px', fontSize: 12, color: 'var(--text-dimmer)', lineHeight: 1.95 }}>
        نزّل القالب، املأ عمود التكلفة والمورد في أي برنامج جداول، ثم ارفعه هنا.
        سترى كل صفّ وما سيفعله قبل أن يُكتب شيء. الاستيراد لا ينشر أي منتج —
        قرار النشر يبقى قراراً منفصلاً تتّخذه أنت.
      </p>

      <p style={{ margin: '0 0 16px', display: 'flex', gap: 9, flexWrap: 'wrap', alignItems: 'center' }}>
        <a href="/admin/store/import/template" className="btn-ghost"
          data-testid="import-template" style={{ fontSize: 12.5 }}>
          نزّل القالب (CSV)
        </a>
        <label className="btn-primary" style={{ fontSize: 12.5, cursor: 'pointer' }}>
          اختر ملفاً
          <input
            type="file"
            accept=".csv,text/csv"
            data-testid="import-file"
            onChange={async e => {
              const f = e.target.files?.[0];
              e.target.value = '';
              if (!f) return;
              setError(null); setDone(null); setVerdicts(null);
              const text = await f.text();
              setCsv(text);
              setFileName(f.name);
              setPending(true);
              const r = await previewSupplyCsv(text);
              setPending(false);
              if (!r.ok) { setError(r.errorAr); return; }
              setVerdicts(r.verdicts);
              setCounts({ apply: r.applyCount, skip: r.skipCount, reject: r.rejectCount });
            }}
            style={{ display: 'none' }}
          />
        </label>
        {fileName && <span style={{ fontSize: 11.5, color: 'var(--text-dimmer)' }} className="ltr">{fileName}</span>}
        {pending && <span style={{ fontSize: 11.5, color: 'var(--text-dimmer)' }}>جارٍ الفحص…</span>}
      </p>

      {error && (
        <p role="alert" data-testid="import-error" className="card-sm"
          style={{ padding: '12px 14px', margin: '0 0 14px', fontSize: 12.5, color: 'var(--sev-blocker)', lineHeight: 1.9 }}>
          {error}
        </p>
      )}
      {done && (
        <p role="status" data-testid="import-done" className="card-sm"
          style={{ padding: '12px 14px', margin: '0 0 14px', fontSize: 12.5, color: 'var(--sev-ok)', lineHeight: 1.9 }}>
          {done}
        </p>
      )}

      {verdicts && (
        <>
          <p data-testid="import-summary"
            style={{ margin: '0 0 12px', fontSize: 12.5, lineHeight: 1.9 }}>
            <span style={{ color: 'var(--sev-ok)' }}>سيُطبَّق: <span dir="ltr">{counts.apply}</span></span>
            {' · '}
            <span style={{ color: 'var(--text-dimmer)' }}>يُترك كما هو: <span dir="ltr">{counts.skip}</span></span>
            {' · '}
            <span style={{ color: 'var(--sev-blocker)' }}>مرفوض: <span dir="ltr">{counts.reject}</span></span>
          </p>

          <div style={{ overflowX: 'auto', maxHeight: 420, overflowY: 'auto' }}>
            <table data-testid="import-preview"
              style={{ borderCollapse: 'collapse', width: '100%', minWidth: 420, fontSize: 12 }}>
              <caption className="sr-only">معاينة صفوف الاستيراد وما سيحدث لكل صفّ</caption>
              <thead>
                <tr>
                  <th scope="col" style={th}>الخيار</th>
                  <th scope="col" style={th}>ما سيحدث</th>
                </tr>
              </thead>
              <tbody>
                {verdicts.map((v, i) => (
                  <tr key={i} data-testid={`import-row-${v.kind}`}>
                    <td style={td} className="ltr">{v.variantId || '—'}</td>
                    <td style={{
                      ...td,
                      color: v.kind === 'apply' ? 'var(--sev-ok)'
                        : v.kind === 'reject' ? 'var(--sev-blocker)' : 'var(--text-dimmer)',
                    }}>
                      {v.kind === 'apply'
                        ? `تُسجَّل التكلفة ${(v.unitCostMinor / 100).toFixed(2)} + شحن ${(v.inboundShippingMinor / 100).toFixed(2)} ويُحسب السعر`
                        : v.reasonAr}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <p style={{ margin: '14px 0 0' }}>
            <button type="button" className="btn-primary" data-testid="import-apply"
              disabled={pending || counts.apply === 0}
              onClick={async () => {
                setPending(true); setError(null);
                const r = await applySupplyCsv(csv);
                setPending(false);
                if (!r.ok) { setError(r.errorAr); return; }
                setVerdicts(null);
                setDone(`طُبِّق ${r.applied} صفّاً. تُرك ${r.skipped}، ورُفض ${r.rejected}. `
                  + 'لم يُنشر أي منتج — النشر قرار منفصل.');
              }}
              style={{ fontSize: 13, padding: '10px 20px' }}>
              {pending ? 'جارٍ التطبيق…' : `طبّق ${counts.apply} صفّاً`}
            </button>
          </p>
        </>
      )}
    </section>
  );
};

const th: React.CSSProperties = {
  textAlign: 'start', padding: '7px 9px',
  borderBottom: '1px solid var(--border)', position: 'sticky', top: 0,
  background: 'var(--surface)', fontWeight: 800,
};
const td: React.CSSProperties = {
  textAlign: 'start', padding: '7px 9px',
  borderBottom: '1px solid var(--border-soft)', lineHeight: 1.8,
};
