// Single source of truth for Community Firestore/Storage path shapes.
// Components never hand-build these strings — they call these helpers.

export const POSTS_COLLECTION = 'posts';
export const COMMENTS_SUBCOLLECTION = 'comments';
export const USERS_COLLECTION = 'users';
export const SAVED_POSTS_SUBCOLLECTION = 'savedPosts';
export const REPORTS_COLLECTION = 'reports';

export const postPath = (postId: string): string => `${POSTS_COLLECTION}/${postId}`;

export const commentsPath = (postId: string): string => `${postPath(postId)}/${COMMENTS_SUBCOLLECTION}`;

export const commentPath = (postId: string, commentId: string): string => `${commentsPath(postId)}/${commentId}`;

// Comment likes (Phase 6) — deterministic per-(commentId, uid) document, so
// "one like per user per comment" is a document-existence fact, not
// application-level dedup. Nested under the comment itself, mirroring
// savedPosts' "relation nested under the owner-relevant parent" convention.
export const COMMENT_LIKES_SUBCOLLECTION = 'likes';

export const commentLikesPath = (postId: string, commentId: string): string =>
  `${commentPath(postId, commentId)}/${COMMENT_LIKES_SUBCOLLECTION}`;

export const commentLikePath = (postId: string, commentId: string, uid: string): string =>
  `${commentLikesPath(postId, commentId)}/${uid}`;

// Post likes — mirrors comment likes exactly: a deterministic
// per-(postId, uid) document nested under the post itself, so "one like per
// user per post" is a document-existence fact, not application-level dedup.
export const POST_LIKES_SUBCOLLECTION = 'likes';

export const postLikesPath = (postId: string): string =>
  `${postPath(postId)}/${POST_LIKES_SUBCOLLECTION}`;

export const postLikePath = (postId: string, uid: string): string =>
  `${postLikesPath(postId)}/${uid}`;

export const userPath = (uid: string): string => `${USERS_COLLECTION}/${uid}`;

export const savedPostsPath = (uid: string): string => `${userPath(uid)}/${SAVED_POSTS_SUBCOLLECTION}`;

export const savedPostPath = (uid: string, postId: string): string => `${savedPostsPath(uid)}/${postId}`;

// Follow system (Phase 5) — a single canonical document per relationship,
// nested under the follower's own user document. Document ID is exactly the
// followed user's uid (a single path segment, never a delimited
// concatenation of two uids) — the follower's identity comes from the
// parent path, not from the document ID or its content.
export const FOLLOWING_COLLECTION = 'following';

export const followingPath = (uid: string): string =>
  `${userPath(uid)}/${FOLLOWING_COLLECTION}`;

export const followingRelationPath = (followerUid: string, followedUid: string): string =>
  `${followingPath(followerUid)}/${followedUid}`;

// Storage folder path — matches Firestore Rules' mediaPath == 'community/posts/' + postId
// check exactly. Individual filenames inside this folder are UUID-based
// ({uuid}.jpg, {uuid}_thumb.jpg) — generated by MediaUploader, not by this file.
export const mediaFolderPath = (postId: string): string => `community/posts/${postId}`;
