// Single source of truth for Community Firestore/Storage path shapes.
// Components never hand-build these strings — they call these helpers.

export const POSTS_COLLECTION = 'posts';
export const COMMENTS_SUBCOLLECTION = 'comments';
export const USERS_COLLECTION = 'users';
export const SAVED_POSTS_SUBCOLLECTION = 'savedPosts';
export const REPORTS_COLLECTION = 'reports';

export const postPath = (postId: string): string => `${POSTS_COLLECTION}/${postId}`;

export const commentsPath = (postId: string): string => `${postPath(postId)}/${COMMENTS_SUBCOLLECTION}`;

export const commentPath = (postId: string, commentId: string): string => `${commentsPath(postId)}/${commentId}`;

export const userPath = (uid: string): string => `${USERS_COLLECTION}/${uid}`;

export const savedPostsPath = (uid: string): string => `${userPath(uid)}/${SAVED_POSTS_SUBCOLLECTION}`;

export const savedPostPath = (uid: string, postId: string): string => `${savedPostsPath(uid)}/${postId}`;

// Storage folder path — matches Firestore Rules' mediaPath == 'community/posts/' + postId
// check exactly. Individual filenames inside this folder are UUID-based
// ({uuid}.jpg, {uuid}_thumb.jpg) — generated by MediaUploader, not by this file.
export const mediaFolderPath = (postId: string): string => `community/posts/${postId}`;
