#!/usr/bin/env tsx
/**
 * Turn a captured suite transcript into ONE script that runs on the real
 * project, and turn that script's output back into a transcript with real
 * answers.
 *
 *   emit    read supabase/plan/transcript.jsonl → write remote-probes.sql
 *   absorb  read remote-results.json (the script's rows) → fill the transcript
 *
 * HOW A PROBE STAYS A PROBE
 * =========================
 * A probe must (a) run as `anon`/`authenticated` with a spoofed uid, (b) have
 * its writes undone, and (c) still report what it saw. Locally that is
 * `begin … rollback` and psql prints the rows on the way past. Over a single
 * batched script neither half works: a rolled-back transaction takes the
 * answer with it, and one statement's rows are not returned in the middle of
 * a script.
 *
 * So each probe runs inside a plpgsql SUBTRANSACTION which is always undone,
 * and its answer leaves through the exception that undoes it:
 *
 *     begin
 *       execute 'set local role …';  execute <the probe>;
 *       raise exception using message = '<sentinel>' || answer;   -- undo + carry
 *     exception when others then
 *       <sentinel> present → the answer;  absent → a genuine denial
 *     end;
 *
 * `set local role` and the JWT GUC are transaction-scoped, so they unwind with
 * the subtransaction too — every probe starts from the same clean footing.
 * Denials arrive as the database's own error text, which is what the suites
 * already treat as «refused».
 *
 * Statements that are NOT probes (seeds, cleanup, introspection) run plainly
 * in order, exactly as the suite issued them.
 *
 * Run: npx tsx scripts/supabaseRemoteBatch.ts emit
 *      npx tsx scripts/supabaseRemoteBatch.ts absorb
 */

import path from 'node:path';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { readTranscript, writeTranscript, type TranscriptEntry } from './lib/sqlTranscript';
import { splitSql } from './lib/migrationPlan';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const mode = process.argv[2];
const tPath = path.join(ROOT, process.env.SUPABASE_TRANSCRIPT_FILE ?? 'supabase/plan/transcript.jsonl');
const sqlPath = path.join(ROOT, 'supabase/plan/remote-probes.sql');
const resPath = path.join(ROOT, 'supabase/plan/remote-results.json');

const SENTINEL = '__probe_ok__';

/** `$q0$…$q0$` with a tag that cannot appear inside the text it quotes. */
function dollarQuote(s: string, i: number): string {
  let tag = `q${i}`;
  while (s.includes(`$${tag}$`)) tag = `${tag}x`;
  return `$${tag}$${s}$${tag}$`;
}

if (mode === 'emit') {
  const entries = readTranscript(tPath);
  const parts: string[] = [
    '-- Generated by scripts/supabaseRemoteBatch.ts — do not edit by hand.',
    '-- Runs one captured suite against the real project, probe by probe.',
    '',
    'create temp table _probe_out (i int primary key, okd boolean, out text);',
    '',
    `create or replace function pg_temp.run_probe(i int, stmts text[])`,
    'returns void language plpgsql as $fn$',
    'declare',
    '  s text; answer text; last_i int := array_length(stmts, 1);',
    'begin',
    '  begin',
    '    for idx in 1 .. last_i loop',
    '      s := stmts[idx];',
    // INTO is only legal for a statement that returns rows. A probe whose last
    // statement is a bare INSERT/UPDATE is asking «was I allowed?», not «what
    // did I see» — answering it with INTO would turn every permitted write
    // into a fake denial.
    "      if idx = last_i and s ~* '^\\s*(select|with)\\M' then",
    '        execute s into answer;',
    '      else',
    '        execute s;',
    '      end if;',
    '    end loop;',
    `    raise exception using message = '${SENTINEL}' || coalesce(answer, '');`,
    '  exception when others then',
    `    if position('${SENTINEL}' in sqlerrm) = 1 then`,
    `      insert into _probe_out values (i, true, substr(sqlerrm, ${SENTINEL.length + 1}));`,
    '    else',
    '      insert into _probe_out values (i, false, sqlerrm);',
    '    end if;',
    '  end;',
    'end $fn$;',
    '',
  ];

  let probes = 0;
  let plain = 0;
  for (const e of entries) {
    const stmts = splitSql(e.sql).filter(s => s.trim());
    const isProbe = /^\s*begin\b/i.test(stmts[0] ?? '');
    if (isProbe) {
      // Drop the `begin` (the subtransaction replaces it) and any trailing
      // `rollback` (the raise replaces that too).
      const body = stmts.slice(1).filter(s => !/^\s*rollback\s*$/i.test(s));
      const arr = body.map((s, j) => dollarQuote(s, j)).join(', ');
      parts.push(`select pg_temp.run_probe(${e.i}, array[${arr}]);`);
      probes += 1;
    } else if (stmts.length === 1 && /^\s*select\b/i.test(stmts[0])) {
      // A bare SELECT the suite reads an ANSWER from — introspection, or a
      // check on what a trigger wrote. Its result must survive to the replay,
      // so it is captured rather than merely executed.
      parts.push(`insert into _probe_out values (${e.i}, true, `
        + `coalesce((${stmts[0].trim()})::text, ''));`);
      plain += 1;
    } else {
      // Seeds and cleanup: run for real, in order. A failure here aborts the
      // whole script, which is correct — a seed that does not land makes every
      // later answer meaningless.
      parts.push(`${e.sql.trim().replace(/;\s*$/, '')};`);
      parts.push(`insert into _probe_out values (${e.i}, true, '');`);
      plain += 1;
    }
  }

  parts.push('', 'select i, okd, out from _probe_out order by i;');
  writeFileSync(sqlPath, parts.join('\n') + '\n');
  console.log(`✓ ${path.relative(ROOT, sqlPath)}: ${probes} فحصاً معزولاً + ${plain} عبارة مباشرة `
    + `(${entries.length} إجمالاً)`);
  console.log('  نفّذه على المشروع الحقيقي، واحفظ الصفوف في '
    + path.relative(ROOT, resPath));
  process.exit(0);
}

if (mode === 'absorb') {
  const entries = readTranscript(tPath);
  const rows = JSON.parse(readFileSync(resPath, 'utf8')) as
    Array<{ i: number; okd: boolean; out: string | null }>;
  const byIndex = new Map(rows.map(r => [Number(r.i), r]));

  let missing = 0;
  const filled: TranscriptEntry[] = entries.map(e => {
    const r = byIndex.get(e.i);
    if (!r) { missing += 1; return e; }
    return r.okd
      ? { ...e, out: r.out ?? '' }
      : { ...e, out: '', err: `ERROR: ${r.out ?? 'denied'}` };
  });

  writeTranscript(tPath, filled);
  const denials = filled.filter(e => e.err).length;
  console.log(`✓ استوعبت ${rows.length} نتيجة — ${denials} رفضاً من قاعدة البيانات`
    + (missing ? ` · ⚠ ${missing} عبارة بلا نتيجة` : ''));
  if (missing) process.exit(1);
  process.exit(0);
}

console.error('استعمال: supabaseRemoteBatch.ts emit | absorb');
process.exit(2);
